server:
  port: 80
  tomcat:
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: /tmp
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tencent.wxcloudrun.model
  configuration:
    map-underscore-to-camel-case: true

upload:
  path: ${user.home}/uploads

# 配置异步任务执行器
async:
  executor:
    core-pool-size: 2
    max-pool-size: 5
    queue-capacity: 10
