server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

upload:
  path: /path/to/upload/directory

# 配置异步任务执行器
async:
  executor:
    core-pool-size: 2
    max-pool-size: 5
    queue-capacity: 10
